<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog" Version="4.3.1-dev-02385" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="9.0.0-dev-02304" />
    <PackageReference Include="Serilog.Extensions.Logging.File" Version="9.0.0-dev-02302" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="9.0.1-dev-02317" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Serilog.Sinks.RollingFile" Version="3.3.1-dev-00771" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="log\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WongaApplication.Application\WongaApplication.Application.csproj" />
    <ProjectReference Include="..\WongaApplication.Infrastructure\WongaApplication.Infrastructure.csproj" />
  </ItemGroup>

</Project>
